Repository MapColonies/image-exporter-client, pull requests merged in 2020-12, with the labels that each got.

#131 feat(max zoom): add option to select exported geopackages max zoom
  README.md
  confd/production.tmpl
  confd/production.toml
  src/__mocks-data__/exportedPackages.ts
  src/common/config/index.ts
  src/common/i18n/en.json
  src/common/i18n/he.json
  src/exporter/components/export-table/export-table-dialog.tsx
  src/exporter/components/export/__snapshots__/export-dialog.spec.tsx.snap
  src/exporter/components/export/export-dialog.tsx
  src/exporter/components/map-container/__snapshots__/dialog-bbox.spec.tsx.snap
  src/exporter/components/map-container/dialog-bbox.tsx
  src/exporter/models/exportTaskStatus.ts
  src/exporter/models/exporterStore.ts
  src/exporter/views/exporter-view.tsx
Labels: enhancement

#136 fix: revert docker Linux uncompilable optimization
  Dockerfile
Labels: bug

#139 feat(max zoom): add option to select exported geopackages max zoom
  src/common/i18n/en.json
  src/common/i18n/he.json
  src/common/models/exportStoreError.ts
  src/exporter/components/export/__snapshots__/export-dialog.spec.tsx.snap
  src/exporter/components/export/export-dialog.spec.tsx
  src/exporter/components/export/export-dialog.tsx
  src/exporter/views/exporter-view.tsx
Labels: bug, enhancement

#154 fix(snackbar): show snackbar on server error when fetching export list
  src/exporter/models/exporterStore.ts
Labels: bug
